unique_ids:
  assets:
    standard-page.html: GOBTJIV6MQBE3P3FVBIA6FMDEDPIA2PS
    theme.css: T56Q2K2NPHR2F4U3PYQHIFHDB5F66LSO
  forms:
    addCustomer: '1734472210661856892080088.8378'
    home: SBLKMCWEU4YJLLMDEWKMVED6LH7KITZ3
  modules: {}
  scripts: {}
  server_modules: {}
